# Generated by Django 6.0.6 on 2026-06-12 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_patient_options_patient_queue_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(help_text='Patient chief complaint as noted by doctor')),
                ('history_of_illness', models.TextField(blank=True, default='', help_text='History of present illness')),
                ('physical_examination', models.TextField(blank=True, default='', help_text='Physical examination findings')),
                ('diagnosis', models.TextField(help_text='Doctor diagnosis or provisional diagnosis')),
                ('diagnosis_type', models.CharField(choices=[('provisional', 'Provisional diagnosis'), ('confirmed', 'Confirmed diagnosis'), ('referred', 'Referred'), ('follow_up', 'Follow-up required')], default='provisional', max_length=20)),
                ('treatment_plan', models.TextField(blank=True, default='', help_text='Proposed treatment plan')),
                ('prescriptions', models.TextField(blank=True, default='', help_text='Medications prescribed')),
                ('lab_tests_ordered', models.TextField(blank=True, default='', help_text='Lab tests ordered for this visit')),
                ('follow_up_date', models.DateField(blank=True, help_text='Next follow-up date', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultations',
                'ordering': ['-created_at'],
            },
        ),
    ]
