# Generated by Django 6.0.6 on 2026-06-11 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Temperature in °C', max_digits=4)),
                ('blood_pressure', models.CharField(help_text='e.g. 120/80 mmHg', max_length=20)),
                ('pulse_rate', models.PositiveIntegerField(help_text='Beats per minute')),
                ('respiratory_rate', models.PositiveIntegerField(help_text='Breaths per minute')),
                ('weight', models.DecimalField(decimal_places=1, help_text='Weight in kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=1, help_text='Height in cm', max_digits=5)),
                ('chief_complaint', models.TextField(help_text='Main reason for visit')),
                ('symptoms', models.TextField(blank=True, default='', help_text='Additional symptoms')),
                ('urgency_level', models.CharField(choices=[('low', 'Low — routine'), ('medium', 'Medium — needs attention'), ('high', 'High — urgent'), ('critical', 'Critical — immediate')], default='low', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional nurse notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Triage Record',
                'verbose_name_plural': 'Triage Records',
                'db_table': 'triage_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
