# Generated by Django 6.0.6 on 2026-06-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('lab_staff', 'Laboratory Staff'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
    ]
