# Generated by Django 6.0.6 on 2026-06-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('lab_staff', 'Laboratory Staff'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
    ]
