# Generated by Django 6.0.6 on 2026-06-10 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('view_result', 'View Result'), ('download_result', 'Download Result'), ('upload_result', 'Upload Result'), ('update_result', 'Update Result'), ('delete_result', 'Delete Result'), ('create_patient', 'Create Patient'), ('update_patient', 'Update Patient'), ('delete_patient', 'Delete Patient'), ('send_notification', 'Send Notification'), ('change_password', 'Change Password'), ('update_profile', 'Update Profile'), ('other', 'Other')], max_length=50)),
                ('affected_entity', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
